### ISSUE TITLE
use manifest for package build set

### ISSUE THREAD

**Issue by mtmorgan** [vjcitn/BiocBBSpack#10]
https://github.com/vjcitn/BiocBBSpack/blob/8bb814f64969b0c3c031df9366c75f0ef5ebe3ca/R/getpk.R#L21

The published repository only has built packages, so for instance never has a newly added package or does contain a package that has been made defunct during the current release cycle. Instead use git@git.bioconductor.org:admin/manifest which has master (devel) and RELEEASE_* branches.

**Comment by vjcitn** [comment]
done
